version: '3'
services:
  pike13sync:
    build: .
    container_name: pike13sync
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
    volumes:
      - ./config:/app/config
      - ./credentials:/app/credentials
      - ./logs:/app/logs
    restart: unless-stoppedversion: '3'
